day05/ex01/tweetos_aka_hello_rails/config/routes.rb
Rails.application.routes.draw do

   get 'users' => 'users#index'
   get 'comments' => 'comments#index'
   get 'cuicuis' => 'cuicuis#index'
   get 'likes' => 'likes#index'

end

day05/ex01/tweetos_aka_hello_rails/app/models/comment.rb
class Comment < ActiveRecord::Base

end

day05/ex01/tweetos_aka_hello_rails/app/models/cuicui.rb
class Cuicui < ActiveRecord::Base

  # scope :top, lambda { implementez ici }

  def fame

  end

end

day05/ex01/tweetos_aka_hello_rails/app/models/like.rb
class Like < ActiveRecord::Base


end

day05/ex01/tweetos_aka_hello_rails/app/models/user.rb
class User < ActiveRecord::Base

end

day05/ex01/tweetos_aka_hello_rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

day05/ex01/tweetos_aka_hello_rails/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:content, :cuicui_id, :user_id)
  end
end

day05/ex01/tweetos_aka_hello_rails/app/controllers/cuicuis_controller.rb
class CuicuisController < ApplicationController
  before_action :set_cuicui, only: [:show, :edit, :update, :destroy]

  # GET /cuicuis
  # GET /cuicuis.json
  def index
    @cuicuis = Cuicui.all
  end

  # GET /cuicuis/1
  # GET /cuicuis/1.json
  def show
  end

  # GET /cuicuis/new
  def new
    @cuicui = Cuicui.new
  end

  # GET /cuicuis/1/edit
  def edit
  end

  # POST /cuicuis
  # POST /cuicuis.json
  def create
    @cuicui = Cuicui.new(cuicui_params)

    respond_to do |format|
      if @cuicui.save
        format.html { redirect_to @cuicui, notice: 'Cuicui was successfully created.' }
        format.json { render :show, status: :created, location: @cuicui }
      else
        format.html { render :new }
        format.json { render json: @cuicui.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cuicuis/1
  # PATCH/PUT /cuicuis/1.json
  def update
    respond_to do |format|
      if @cuicui.update(cuicui_params)
        format.html { redirect_to @cuicui, notice: 'Cuicui was successfully updated.' }
        format.json { render :show, status: :ok, location: @cuicui }
      else
        format.html { render :edit }
        format.json { render json: @cuicui.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cuicuis/1
  # DELETE /cuicuis/1.json
  def destroy
    @cuicui.destroy
    respond_to do |format|
      format.html { redirect_to cuicuis_url, notice: 'Cuicui was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cuicui
    @cuicui = Cuicui.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cuicui_params
    params.require(:cuicui).permit(:content, :user_id)
  end
end

day05/ex01/tweetos_aka_hello_rails/app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like, only: [:show, :edit, :update, :destroy]

  # GET /likes
  # GET /likes.json
  def index
    @likes = Like.all
  end

  # GET /likes/1
  # GET /likes/1.json
  def show
  end

  # GET /likes/new
  def new
    @like = Like.new
  end

  # GET /likes/1/edit
  def edit
  end

  # POST /likes
  # POST /likes.json
  def create
    @like = Like.new(like_params)

    respond_to do |format|
      if @like.save
        format.html { redirect_to @like, notice: 'Like was successfully created.' }
        format.json { render :show, status: :created, location: @like }
      else
        format.html { render :new }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /likes/1
  # PATCH/PUT /likes/1.json
  def update
    respond_to do |format|
      if @like.update(like_params)
        format.html { redirect_to @like, notice: 'Like was successfully updated.' }
        format.json { render :show, status: :ok, location: @like }
      else
        format.html { render :edit }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /likes/1
  # DELETE /likes/1.json
  def destroy
    @like.destroy
    respond_to do |format|
      format.html { redirect_to likes_url, notice: 'Like was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_like
    @like = Like.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def like_params
    params.require(:like).permit(:cuicui_id, :user_id)
  end
end

day05/ex01/tweetos_aka_hello_rails/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :email, :since, :admin, :country)
  end
end

day05/ex01/tweetos_aka_hello_rails/app/helpers/application_helper.rb
module ApplicationHelper
end

day05/ex01/tweetos_aka_hello_rails/app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :cuicui_id %><br>
    <%= f.text_field :cuicui_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

day05/ex01/tweetos_aka_hello_rails/app/views/comments/edit.html.erb
<!-- comment -->
<%if false%>
<% title "Editing Comment"%>
<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>





<%end%>

day05/ex01/tweetos_aka_hello_rails/app/views/comments/index.html.erb
<!-- comment -->
<%if false%>
<p id="notice"><%= notice %></p>

<% title "Listing Comments"%>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Cuicui</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= comment.cuicui.content[0,20] %>..</td>
        <td><%= comment.user.name %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>





<%end%>

day05/ex01/tweetos_aka_hello_rails/app/views/comments/new.html.erb
<!-- comment -->
<%if false%>
<% title "New Comment"%>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>





<%end%>

day05/ex01/tweetos_aka_hello_rails/app/views/comments/show.html.erb
<!-- comment -->
<%if false%>
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>Cuicui:</strong>
  <%= @comment.cuicui %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>


<%end%>

day05/ex01/tweetos_aka_hello_rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TAHR <%= yield :title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="buttons set black">

    <%= link_to "cuicuis" ,cuicuis_path ,method: :get, class: "btn pri Blacklist"%>
    <%= link_to "comments" ,comments_path ,method: :get, class: "btn pri Blacklist"%>
    <%= link_to "likes" ,likes_path ,method: :get , class: "btn pri Blacklist"%>
    <%= link_to "users" ,users_path ,method: :get, class: "btn pri Blacklist"%>
  </div>
  <h1><%= yield(:title) %></h1>
<%= yield %>

</body>
</html>